### PR TITLE
setup project

### PR DESCRIPTION
**Pull request by fickryiman**
npx create-react-app math-magicians
setup linters (react-redux)
setup gitflow
add descriptive README

### CODE REVIEW

**Review by aamirkhan2478 — COMMENTED** [review]
Hi @fickryiman, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that hasn't a PR summary kindly add a PR descriptive summary and also your PR title is not descriptive kindly edit your PR title as well :+1:  check below :point_down: the example of PR descriptive title and summary

219520522-f0a8c7ba-b272-4a26-81c7-c233913f9c1e

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fickryiman** [comment]
> Hi @fickryiman,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request 🔴 🔴 🔴
> You have submitted a project, that hasn't a PR summary kindly add a PR descriptive summary and also your PR title is not descriptive kindly edit your PR title as well 👍 check below 👇 the example of PR descriptive title and summary
> 
> 219520522-f0a8c7ba-b272-4a26-81c7-c233913f9c1e
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hi Reviewer,

The screenshot PR is not my PR.
I think you have a review mistaken.

Please help to check again.

**Comment by fickryiman** [comment]
Add descriptive PR summary

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🎉✔🍾**
Hello @fickryiman 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Descriptive README.
- Passing linters.
- Nice implementation of project requirements.


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
